// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiteAgencia.Models;

namespace SiteAgencia.Migrations
{
    [DbContext(typeof(Conectar))]
    [Migration("20211214150317_Agencia-Viagens")]
    partial class AgenciaViagens
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SiteAgencia.Models.Cliente", b =>
                {
                    b.Property<int>("id_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Clienteid_cliente")
                        .HasColumnType("int");

                    b.Property<int?>("Comprasid_compra")
                        .HasColumnType("int");

                    b.Property<string>("cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_cliente");

                    b.HasIndex("Clienteid_cliente");

                    b.HasIndex("Comprasid_compra");

                    b.ToTable("CadastroCliente");
                });

            modelBuilder.Entity("SiteAgencia.Models.Compras", b =>
                {
                    b.Property<int>("id_compra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("id_cliente")
                        .HasColumnType("int");

                    b.Property<int>("id_destino")
                        .HasColumnType("int");

                    b.HasKey("id_compra");

                    b.ToTable("CadastroCompra");
                });

            modelBuilder.Entity("SiteAgencia.Models.Destinos", b =>
                {
                    b.Property<int>("id_Destino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Comprasid_compra")
                        .HasColumnType("int");

                    b.Property<int?>("Destinosid_Destino")
                        .HasColumnType("int");

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("destino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("valor")
                        .HasColumnType("real");

                    b.HasKey("id_Destino");

                    b.HasIndex("Comprasid_compra");

                    b.HasIndex("Destinosid_Destino");

                    b.ToTable("CadastroDestino");
                });

            modelBuilder.Entity("SiteAgencia.Models.Cliente", b =>
                {
                    b.HasOne("SiteAgencia.Models.Cliente", null)
                        .WithMany("cliente")
                        .HasForeignKey("Clienteid_cliente");

                    b.HasOne("SiteAgencia.Models.Compras", null)
                        .WithMany("cliente")
                        .HasForeignKey("Comprasid_compra");
                });

            modelBuilder.Entity("SiteAgencia.Models.Destinos", b =>
                {
                    b.HasOne("SiteAgencia.Models.Compras", null)
                        .WithMany("destino")
                        .HasForeignKey("Comprasid_compra");

                    b.HasOne("SiteAgencia.Models.Destinos", null)
                        .WithMany("destinos")
                        .HasForeignKey("Destinosid_Destino");
                });

            modelBuilder.Entity("SiteAgencia.Models.Cliente", b =>
                {
                    b.Navigation("cliente");
                });

            modelBuilder.Entity("SiteAgencia.Models.Compras", b =>
                {
                    b.Navigation("cliente");

                    b.Navigation("destino");
                });

            modelBuilder.Entity("SiteAgencia.Models.Destinos", b =>
                {
                    b.Navigation("destinos");
                });
#pragma warning restore 612, 618
        }
    }
}
